### ISSUE TITLE
Update README `installation` information

### ISSUE THREAD

**Issue by alisonlhart** [redhat-cop/network.interfaces#13]
This section https://github.com/redhat-cop/network.interfaces#installation in the README needs to be updated with the correct install information.

Since the collection is now on Automation Hub, instead of installing from `ansible-galaxy collection install git+https://github.com/redhat-cop/network.interfaces` , install directly with the collection name: `ansible-galaxy collection install network.interfaces`.

The requirements.yml section should also be updated to show `network.interfaces` instead of the repository link.

Any other install references (if relevant) should be updated in the same way.

If there is no upcoming release planned to Automation Hub, please make a one-off minor release for this fix, so customers can receive the updated docs as soon as possible.

**Comment by NilashishC** [comment]
As a reference: https://github.com/redhat-cop/network.telemetry#installation
