### ISSUE TITLE
add support for EOS

### ISSUE THREAD

**Issue by KB-perByte** [redhat-cop/network.interfaces#19]
https://github.com/redhat-cop/network.interfaces/blob/2c168fd72d2b79a24f1c52efc51f9f9208042d6f/roles/run/tasks/includes/health_checks/eos.yaml#L4

EOS command reference is empty, proper support for EOS needs to be added.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

network.interfaces/eos
##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by ashwini-mhatre** [comment]
Issue is fixed

**Comment by trishnaguha** [comment]
Does this need to happen for all validated content @KB-perByte @ashwini-mhatre ?

**Comment by KB-perByte** [comment]
Hey @trishnaguha I see it was corrected for network.interfaces https://github.com/redhat-cop/network.interfaces/pull/21 all the other validated content have implementations for EOS now.
Regards.
